spring:
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #默认的key序列化器是StringSerializer，如果不指定，默认就是StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

    template:
      default-topic: default-topic
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest