spring:
  profiles:
    active: dev
  kafka:
    listener:
      ack-mode: manual
      #设置监听器一次监听一组消息
      type: single
    #      type: batch

    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    #?????
    #?????
    template:
      default-topic: ${spring.kafka.template.default-topic}
    producer:
#        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ${spring.kafka.producer.value-serializer}
      key-serializer: ${spring.kafka.producer.key-serializer}
    consumer:
      #设置监听一组的最大数
      max-poll-records: 20
        #默认消费最新消息，如果没有这个配置，默认是latest
      auto-offset-reset: ${spring.kafka.consumer.auto-offset-reset}
      key-deserializer: ${spring.kafka.consumer.key-deserializer}
      value-deserializer: ${spring.kafka.consumer.value-deserializer}
kafka:
  topic:
    name: hello-topic3
  consumer:
    group-id: batchgroup2


