spring:
  profiles:
    active: dev
  kafka:
    listener:
      ack-mode: manual
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    #?????
    consumer:
      #默认消费最新消息，如果没有这个配置，默认是latest
      auto-offset-reset: ${spring.kafka.consumer.auto-offset-reset}

    #?????
    template:
      default-topic: ${spring.kafka.template.default-topic}
    producer:
#        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ${spring.kafka.producer.value-serializer}
      key-serializer: ${spring.kafka.producer.key-serializer}


kafka:
  topic:
    name: hello-topic
  consumer:
    group-id: helloGroup3


